const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const partSchema = new Schema({

  part_number: { type: String, required: true, trim: true },
  part_description: String,
  part_detail: String,
  uom: String,
  part_type: String,
  active: String,
  abc_code: String,
  weight: String,
  weight_uom: String,
  width: String,
  height: String,
  length: String,
  size_uom: String,
  primary_tracking: String,
  tracks_lot_number: String,
  tracks_serial_number: String,
  tracks_asset_tag: String,
  tracks_condition: String,
  tracks_brang: String,
  cf_mpn: String,
  cf_max_spec_needed: String,
  cf_integration_manual_needed: String,
  cf_raid_image_needed: String,
  cf_cpu_type: String,
  cf_processor: String,
  cf_cpu_base_frequency: String,
  cf_screen_size: String,
  cf_display_type: String,
  cf_display_long_form: String,
  cf_screen_resolution: String,
  cf_touchscreen: String,
  cf_ips: String,
  cf_120hz: String,
  cf_144hz: String,
  cf_240hz: String,
  cf_5ms_response_time: String,
  cf_3ms_response_time: String,
  cf_g_sync: String,
  cf_graphics_card: String,
  cf_vram: String,
  cf_vr_ready: String,
  cf_ram_size: String,
  cf_ram_type: String,
  cf_ram_speed: String,
  cf_max_ram_capability: String,
  cf_ssd: String,
  cf_ssd_type: String,
  cf_raid: String,
  cf_hdd: String,
  cf_hdd_speed_rpm: String,
  cf_optical_drive: String,
  cf_operating_system: String,
  cf_wireless: String,
  cf_wifi_brand: String,
  cf_bluetooth: String,
  cf_usb_ports: String,
  cf_usb_type_c: String,
  cf_video_ports: String,
  cf_thunderbolt: String,
  cf_audio_ports: String,
  cf_card_reader: String,
  cf_keyboard: String,
  cf_backlit_keyboard: String,
  cf_fingerprint_reader: String,
  cf_webcam: String,
  cf_battery: String,
  cf_power_supply: String,
  cf_item_length: String,
  cf_item_width: String,
  cf_item_height: String,
  cf_item_weight: String,

  
});

const part = mongoose.model('part', partSchema);
module.exports = part;